[Configuration]
BasedOn=..\UDKGame\Config\DefaultEngineUDK.ini

[UnrealEd.EditorEngine]
+EditPackages=TestPackage
; +EditPackages=AkAudio
; +EditPackages=PlatformCommon
; +EditPackages=TgGame
; +EditPackages=TgClient
; +EditPackages=TgMod
; +EditPackages=TempestMp
