[mod]
id = "Tempest Core"
name = "Tempest Core"
version = "0.57"

[[mod.authors]]
name = "Cinnamon 🇧🇪"
link = "https://github.com/SupImCinnamon"

[[mod.authors]]
name = "Tom"
link = "https://github.com/Xiloe"

[[mod.authors]]
name = "Kyiro"
link = "https://github.com/Kyiro"
