class TgAIBehaviorObject extends Object
    abstract
    native(AI)
    hidecategories(Object)
    config(Engine);

const BNT_NONE = 0;

const BNT_COMPOSITE_SEQUENCE = 1;

const BNT_COMPOSITE_SEQUENCE_SCRIPTED = 2;

const BNT_COMPOSITE_RANDOM = 3;

const BNT_COMPOSITE_GATED = 4;

const BNT_SENSOR_GODS = 8;

const BNT_SENSOR_SIGHT_RADIUS = 9;

const BNT_SENSOR_TOWERS = 10;

const BNT_SENSOR_IN_HOSTILE_ABILITY = 11;

const BNT_SENSOR_PURCHASE_SKILLS = 12;

const BNT_SENSOR_SAFE_TO_RECALL = 13;

const BNT_SENSOR_LEASH = 14;

const BNT_SENSOR_LANE = 15;

const BNT_SENSOR_DEVICE_TARGETING = 16;

const BNT_SENSOR_INCOMING_DAMAGE = 17;

const BNT_SENSOR_RALLY_POINTS = 18;

const BNT_SENSOR_FORTRESS = 21;

const BNT_CONDITION_IS_AT_SPAWN = 256;

const BNT_CONDITION_IS_SAFE_TO_RECALL = 257;

const BNT_CONDITION_IS_IN_HOSTILE_ABILITY = 258;

const BNT_CONDITION_CAN_PURCHASE_ITEMS = 259;

const BNT_CONDITION_CAN_PURCHASE_SKILLS = 260;

const BNT_CONDITION_COMBAT_DAMAGEABLE = 261;

const BNT_CONDITION_COMBAT_DAMAGEABLE_DEVICE = 262;

const BNT_CONDITION_COMBAT_HEALTH_PERCENT = 263;

const BNT_CONDITION_CURRENT_LEVEL = 264;

const BNT_CONDITION_DEVICE_READY = 265;

const BNT_CONDITION_COMBAT_HAS_TARGET = 266;

const BNT_CONDITION_LANE_HAS_TARGET = 267;

const BNT_CONDITION_HEALTH_PERCENT = 268;

const BNT_CONDITION_COMBAT_IS_HOSTILE = 269;

const BNT_CONDITION_COMBAT_IS_OF_TYPE = 270;

const BNT_CONDITION_IS_IN_MINOTAUR_RADIUS = 271;

const BNT_CONDITION_IS_IN_TOWER_RADIUS = 272;

const BNT_CONDITION_IS_TARGET_OF_TWR_OR_MTR = 273;

const BNT_CONDITION_COMBAT_IS_IN_DISTANCE = 274;

const BNT_CONDITION_NEARBY_GOD_COUNT = 275;

const BNT_CONDITION_NEARBY_GOD_DELTA = 276;

const BNT_CONDITION_NEARBY_TARGET_TYPE_COUNT = 277;

const BNT_CONDITION_NEARBY_TARGET_TYPE_DELTA = 278;

const BNT_CONDITION_COMBAT_IS_TARGETING_TYPE = 279;

const BNT_CONDITION_MANA_PERCENT = 280;

const BNT_CONDITION_MINIONS_IN_TOWER_RADIUS = 281;

const BNT_CONDITION_DISTANCE_FROM_SPAWN = 282;

const BNT_CONDITION_COMBAT_IS_VISIBLE = 283;

const BNT_CONDITION_TIME_SINCE_TOOK_DAMAGE = 284;

const BNT_CONDITION_COMBAT_IS_IN_MINOTAUR_RADIUS = 285;

const BNT_CONDITION_COMBAT_IS_IN_TOWER_RADIUS = 286;

const BNT_CONDITION_COMBAT_IS_TARGET_OF_TWR_OR_MTR = 287;

const BNT_CONDITION_DISTANCE_FROM_SELECTED_TARGET = 288;

const BNT_CONDITION_COMBAT_IS_STEALTHED = 289;

const BNT_CONDITION_COMBAT_IS_LOOKING_AT = 290;

const BNT_CONDITION_DISTANCE_FROM_COMBAT_TARGET = 291;

const BNT_CONDITION_IS_LAST_ATTACKER_OF_TYPE = 292;

const BNT_CONDITION_SELECTED_TARGET_HEALTH_PCT = 293;

const BNT_CONDITION_GODS_IN_TOWER_RADIUS = 294;

const BNT_CONDITION_NEAREST_TOWER_HEALTH_PCT = 295;

const BNT_CONDITION_COMBAT_IS_IN_FOUNTAIN = 296;

const BNT_CONDITION_COMBAT_IS_IN_LEASH = 297;

const BNT_CONDITION_COMBAT_IS_IN_SIGHT_RADIUS = 298;

const BNT_CONDITION_IS_OUTSIDE_LEASH = 299;

const BNT_CONDITION_TIMER = 300;

const BNT_CONDITION_HAS_SPREAD_LOCATION = 301;

const BNT_CONDITION_TARGET_TYPE_IS_IN_LEASH = 302;

const BNT_CONDITION_ENERGY = 303;

const BNT_CONDITION_COMBAT_DAMAGED_FRIENDLY_GOD = 304;

const BNT_CONDITION_IS_TOO_FAR_FROM_LANE = 305;

const BNT_CONDITION_COMBAT_HAS_EFFECT_CATEGORY = 306;

const BNT_CONDITION_HAS_EFFECT_CATEGORY = 307;

const BNT_CONDITION_TARGETS_DAMAGEABLE_BY_DEVICE = 308;

const BNT_CONDITION_GAMETYPE = 309;

const BNT_CONDITION_COMBAT_IS_LAST_ATTACKER = 310;

const BNT_CONDITION_DIFFICULTY_LEVEL = 311;

const BNT_CONDITION_INCOMING_DAMAGE = 312;

const BNT_CONDITION_HAS_CONSUMABLE = 313;

const BNT_CONDITION_HAS_ACTIVE = 314;

const BNT_CONDITION_DISTANCE_FROM_LANE_TARGET = 315;

const BNT_CONDITION_IS_ACTIVE_READY = 316;

const BNT_CONDITION_TASKFORCE = 317;

const BNT_CONDITION_COMBAT_HEALTH_AFTER_ATTACK = 318;

const BNT_CONDITION_RETURN_ALWAYS = 319;

const BNT_CONDITION_LAST_ATTACKER_IS_TARGET_TYPE = 320;

const BNT_CONDITION_DEVICE_IS_FIRING = 321;

const BNT_CONDITION_COMBAT_DROPPED = 322;

const BNT_CONDITION_IS_AT_RALLY_POINT = 323;

const BNT_CONDITION_NUM_RALLY_POINTS = 324;

const BNT_CONDITION_PET_PHASE = 325;

const BNT_CONDITION_PHYSICS_STATE = 326;

const BNT_CONDITION_COMBAT_PHYSICS_STATE = 327;

const BNT_CONDITION_DISTANCE_FROM_NAVIGATION_DESTINATION = 330;

const BNT_CONDITION_SQUAD_AVERAGE_DISTANCE = 331;

const BNT_CONDITION_HAS_NAVIGATION = 332;

const BNT_CONDITION_DISTANCE_FROM_OWNER = 333;

const BNT_CONDITION_COMBAT_TARGET_DISTANCE_OWNER = 334;

const BNT_CONDITION_IS_DECOY_STATE = 335;

const BNT_CONDITION_COMBAT_IS_HITTABLE = 336;

const BNT_CONDITION_IS_META_GAME_STATE = 400;

const BNT_CONDITION_DISTANCE_FROM_LANEPUSHER = 401;

const BNT_CONDITION_IS_AT_ACTIVE_CAPTURE_POINT = 402;

const BNT_CONDITION_DISTANCE_FROM_FORTRESS = 404;

const BNT_CONDITION_IS_IN_FORTRESS = 405;

const BNT_CONDITION_TIME_SINCE_LANEPUSHER_TOOK_DAMAGE = 406;

const BNT_CONDITION_IS_LANEPUSHER_LAST_ATTACKER_OF_TYPE = 407;

const BNT_CONDITION_IS_FORTRESS_VULNERABLE = 408;

const BNT_CONDITION_DISTANCE_FROM_CAPTURE_POINT = 409;

const BNT_CONDITION_DISTANCE_FROM_FORTRESS_OBJECTIVE = 410;

const BNT_CONDITION_COMBAT_TARGET_DISTANCE_FROM_CAPTURE_POINT = 411;

const BNT_CONDITION_GODS_IN_CAPTURE_POINT_RADIUS = 412;

const BNT_CONDITION_CAPTURE_POINT_IS_VISIBLE = 413;

const BNT_CONDITION_COMBAT_IS_LOOKING_AT_CAPTURE_POINT = 414;

const BNT_CONDITION_COMBAT_LANEPUSHER_HEALTH_PERCENT = 415;

const BNT_CONDITION_IS_ACTIVE_CAPTURE_POINT = 416;

const BNT_CONDITION_AMMO_COUNT = 417;

const BNT_CONDITION_AMMO_PER_SHOT = 418;

const BNT_CONDITION_AMMO_AFTER_SHOT = 419;

const BNT_CONDITION_IS_IN_DEVICE_VOLUME = 420;

const BNT_CONDITION_COMBAT_TARGET_INSIDE_DEVICE_VOLUME = 421;

const BNT_CONDITION_LANEPUSHER_IS_VISIBLE = 422;

const BNT_CONDITION_IS_SPAWN_GATE_OPEN = 423;

const BNT_CONDITION_NUM_DEATHS = 424;

const BNT_CONDITION_DELTA_GODS_CAPTURE_POINT = 425;

const BNT_CONDITION_IS_LANEPUSHER_ACTIVE = 426;

const BNT_CONDITION_IS_LANEPUSHER_HOSTILE = 427;

const BNT_CONDITION_DISTANCE_FROM_SQUAD_TARGET = 428;

const BNT_CONDITION_SQUAD_HEALTH_PERCENT = 429;

const BNT_CONDITION_SQUAD_IS_VISIBLE = 430;

const BNT_CONDITION_COMBAT_IS_SHIELDED = 431;

const BNT_CONDITION_SQUAD_IS_SHIELDED = 432;

const BNT_CONDITION_DISTANCE_FROM_SHIELD = 433;

const BNT_CONDITION_TEAM_DEATH_COUNT = 434;

const BNT_CONDITION_GODS_IN_LANE_PUSHER_RADIUS = 435;

const BNT_CONDITION_DISTANCE_FROM_DAMAGING_DEPLOYABLE = 436;

const BNT_CONDITION_DISTANCE_FROM_AVOIDABLE_PROJECTILE = 437;

const BNT_CONDITION_NUM_GODS_NEAR_DEPLOYABLE = 438;

const BNT_CONDITION_NUM_GODS_NEAR_PROJECTILE = 439;

const BNT_CONDITION_WON_LAST_POINT = 440;

const BNT_CONDITION_TIME_IN_PAYLOAD_MODE = 441;

const BNT_CONDITION_IS_ATTACKING_TASK_FORCE = 442;

const BNT_CONDITION_IS_DESIRED_AIM_DEVICE = 443;

const BNT_CONDITION_IS_BOT_BEHAVIOR_STATE = 444;

const BNT_CONDITION_DISTANCE_FROM_ASSAULT_POINT = 445;

const BNT_CONDITION_NEARBY_ALLY_ATTACKED = 446;

const BNT_CONDITION_NUMBER_DEVICES_FIRING = 447;

const BNT_CONDITION_COMBAT_IS_SQUAD_TARGET = 448;

const BNT_CONDITION_SIEGE_SCORE = 449;

const BNT_ACTION_CLEAR_NAVIGATION_QUEUE = 1048576;

const BNT_ACTION_USE_DEVICE = 1048577;

const BNT_ACTION_RUN_TO_SPAWN = 1048578;

const BNT_ACTION_FOLLOW_COMBAT_TARGET = 1048579;

const BNT_ACTION_LOOK_AT_COMBAT_TARGET = 1048580;

const BNT_ACTION_MOVE_TO_LANE_TARGET = 1048581;

const BNT_ACTION_PLAY_EMOTE = 1048582;

const BNT_ACTION_PURCHASE_ITEMS = 1048583;

const BNT_ACTION_PURCHASE_SKILLS = 1048584;

const BNT_ACTION_SELECT_COMBAT_LANE = 1048585;

const BNT_ACTION_SELECT_COMBAT_LASTATTACKER = 1048586;

const BNT_ACTION_SELECT_LANE_MOVE = 1048587;

const BNT_ACTION_SELECT_LANE_JUNGLE = 1048588;

const BNT_ACTION_SELECT_LANE_MINOTAUR = 1048589;

const BNT_ACTION_CLEAR_LANE_MOVE_TARGET = 1048590;

const BNT_ACTION_CLEAR_COMBAT_TARGET = 1048591;

const BNT_ACTION_CLEAR_LOOK_AT = 1048592;

const BNT_ACTION_LEASH_TO_SPAWN = 1048593;

const BNT_ACTION_SELECT_COMBAT_THREAT = 1048594;

const BNT_ACTION_LOOK_AT_SPAWN_ROTATION = 1048595;

const BNT_ACTION_SELECT_COMBAT_LEASH = 1048596;

const BNT_ACTION_RUN_TO_SPREAD_LOCATION = 1048597;

const BNT_ACTION_SELECT_COMBAT_SQUAD = 1048598;

const BNT_ACTION_SUGGEST_COMBAT_SQUAD = 1048599;

const BNT_ACTION_CLEAR_SPREAD_LOCATION = 1048600;

const BNT_ACTION_RUN_TO_OWNER = 1048601;

const BNT_ACTION_FOLLOW_LANE = 1048602;

const BNT_ACTION_CLEAR_LAST_ATTACKER = 1048603;

const BNT_ACTION_SELECT_LANE_MOVE_AS_COMBAT_TARGET = 1048604;

const BNT_ACTION_MOVE_TO_LANE_VOLUME = 1048605;

const BNT_ACTION_JUKE = 1048606;

const BNT_ACTION_USE_CONSUMABLE = 1048607;

const BNT_ACTION_USE_ACTIVE = 1048608;

const BNT_ACTION_FOLLOW_PATROL = 1048609;

const BNT_ACTION_REGEN_HEALTH = 1048610;

const BNT_ACTION_PAUSE_AI = 1048611;

const BNT_ACTION_PLAY_VGS = 1048612;

const BNT_ACTION_ASSIGN_LANE = 1048613;

const BNT_ACTION_SELECT_COMBAT_JUNGLE = 1048614;

const BNT_ACTION_MOVE_TO_RALLY_POINT = 1048615;

const BNT_ACTION_CLEAR_RALLY_POINT = 1048616;

const BNT_ACTION_CANCEL_FIRING = 1048617;

const BNT_ACTION_SELECT_COMBAT_TARGETS_TARGET = 1048618;

const BNT_ACTION_FOLLOW_LANE_REVERSE = 1048619;

const BNT_ACTION_STOP_DEVICE = 1048620;

const BNT_ACTION_STRAFE = 1048621;

const BNT_ACTION_SPREAD_FROM_SQUAD = 1048622;

const BNT_ACTION_MOVE_TO_ASSAULT_POSITION = 1048623;

const BNT_ACTION_MOVE_TO_COVER = 1048624;

const BNT_ACTION_SELECT_COMBAT_OWNER_LASTATTACKER = 1048625;

const BNT_ACTION_SELECT_OWNER_COMBAT_TARGET = 1048626;

const BNT_ACTION_JUMP = 1048627;

const BNT_ACTION_MOVE_TO_DEPLOYABLE = 1048628;

const BNT_ACTION_MOVE_TO_LANEPUSHER = 1048700;

const BNT_ACTION_MOVE_TO_CAPTURE_POINT = 1048701;

const BNT_ACTION_SELECT_LANEPUSHER_COMBAT_TARGET = 1048702;

const BNT_ACTION_SELECT_COMBAT_LANEPUSHER_COMBAT = 1048704;

const BNT_ACTION_SELECT_COMBAT_FORTRESS_OBJECTIVE = 1048705;

const BNT_ACTION_LOOK_AT_FORTRESS = 1048706;

const BNT_ACTION_LOOK_AT_CAPTURE_POINT = 1048707;

const BNT_ACTION_LOOK_AT_LANEPUSHER = 1048708;

const BNT_ACTION_PURCHASE_BURN_CARDS = 1048709;

const BNT_ACTION_MOVE_TO_SHIELD = 1048710;

const BNT_ACTION_MOVE_TO_DAMAGING_DEPLOYABLE = 1048711;

const BNT_ACTION_MOVE_TO_AVOIDABLE_PROJECTILE = 1048712;

const BNT_ACTION_MOVE_AROUND_LANEPUSHER = 1048713;

const BNT_ACTION_GROUP_UP = 1048714;

const BNT_ACTION_WIGGLE = 1048715;

const BNT_ACTION_MOVE_TO_LANEPUSHER_FRONT = 1048716;

const BNT_ACTION_SET_AIM_DEVICE = 1048717;

const BNT_ACTION_SET_BOT_BEHAVIOR_STATE = 1048718;

const BNT_ACTION_RELOAD_DEVICE = 1048719;

const BNT_ACTION_UPDATE_TARGET_LAST_KNOWN_LOCATION = 1048720;

const BNT_ACTION_LOOK_AT_TARGET_LKL = 1048721;

const BNT_ACTION_SELECT_ALLY_ATTACKER_AS_TARGET = 1048722;

const BNT_UTILITY_RANDOM = 268435456;

const BNT_UTILITY_FILTER_GAMESTATE = 268435457;

const BNT_UTILITY_COMBAT_TARGET_DISTANCE = 268435458;

const BNT_UTILITY_FORTRESS_DISTANCE = 268435459;

const BNT_UTILITY_DISTANCE2PAWN = 268435460;

const BNT_UTILITY_FILTER_CAPTUREPOINT = 268435461;

const BNT_UTILITY_FILTER_ASSAULTRANGETYPE = 268435462;

const BNT_UTILITY_FILTER_INSIDE_ACTIVE_RALLY_POINT = 268435463;

const BNT_UTILITY_PAWN_DISTANCE_TO_NORMAL = 268435464;

const BNT_UTILITY_COMBAT_TARGET_DISTANCE_TO_NORMAL = 268435465;

const BNT_UTILITY_FILTER_PAYLOAD = 268435466;

const BNT_UTILITY_FILTER_LOSTOTARGET = 268435467;

const BNT_UTILITY_FILTER_STAYINTARGETFOV = 268435468;

const BNT_UTILITY_FILTER_DISTANCEFROMPAWN = 268435469;

const BNT_UTILITY_FILTER_DISTANCEFROMTARGET = 268435470;

const BNT_UTILITY_FILTER_LOSTOTARGETLASTKNOWNLOCATION = 268435471;

var int NodeToken;
