class TgObject extends Object
    native;

enum GAME_WIN_STATE
{
    GWS_NONE,                       // 0
    GWS_TASKFORCE_TWO_WON,          // 1
    GWS_TASKFORCE_ONE_WON,          // 2
    GWS_TIE,                        // 3
};

enum eTutorialForceableElements
{
    ETBUI_Skills,
    ETBUI_ItemShop,
    ETBUI_ItemShopButton,
    ETBUI_Intro,
    ETBUI_ItemShopWalkthrough,
    ETBUI_ActiveItems,
    ETBUI_ConsumableItems,
    ETBUI_Escape
};

enum TG_GAME_TYPE
{
    TGT_UNSET,
    TGT_CITY,
    TGT_ARENA,
    TGT_ARENA_PRACTICE,
    TGT_ARENA_CAPTURE,
    TGT_ARENA_ESCORT,
    TGT_ARENA_ESCORT_PRACTICE,
    TGT_BATTLE,
    TGT_BATTLE_EXPERT,
    TGT_BATTLE_PRACTICE,
    TGT_BATTLE_JOUST,
    TGT_BATTLE_CASUAL,
    TGT_BATTLE_TRAINING,
    TGT_BATTLE_ARAM,
    TGT_BATTLE_ARAM_PRACTICE,
    TGT_POINTCAPTURE,
    TGT_DOMINATION,
    TGT_SINGLEPOINTCAPTUREANDHOLD,
    TGT_IDOL,
    TGT_SIEGE,
    TGT_BATTLE_TC,
    TGT_BATTLE_SHOOTINGRANGE,
    TGT_CHAOS,
    TGT_CHAOS_PRACTICE,
    TGT_CHAOSRACE,
    TGT_CHAOS_PUSH,
    TGT_CHAOS_PAYLOAD,
    TGT_CHAOS_PAYLOAD_PRACTICE,
    TGT_CHAOS_CAPTUREANDPAYLOAD,
    TGT_CHAOS_CAPTUREANDPAYLOAD_PRACTICE,
    TGT_CHAOS_CAPTUREPOINT,
    TGT_CHAOS_CAPTUREPOINT_PRACTICE,
    TGT_CHAOS_SURVIVAL,
    TGT_CHAOS_SURVIVAL_PRACTICE,
    TGT_CHAOS_SHOOTINGRANGE,
    TGT_CHAOS_TUTORIAL,
    TGT_CHAOS_PVE,
    TGT_CHAOS_PVE_SURVIVAL,
    TGT_CHAOS_TEAM_DEATH_MATCH,
    TGT_CHAOS_ONSLAUGHT,
    TGT_CHAOS_ONSLAUGHT_PRACTICE,
    TGT_CHAOS_ROYALE,
    TGT_CHAOS_ASCENDED_ASSAULT,
    TGT_CHAOS_FLAGBALL,
    TGT_CHAOS_EVENT,
    TGT_CHAOS_END_TIMES,
    TGT_CHAOS_CRAZY_KING,
    TGT_CHAOS_CAPTURE_THE_FLAG,
};

enum AlertType
{
    ATT_Regular,
    ATT_Beneficial,
    ATT_Detrimental,
    ATT_Spectator,
    ATT_Important
};