class TgProperty extends Object
    native
    config(Engine);

const TGPT_FLOAT = 137;

const TGPT_INT = 176;

const TGPT_COMBO = 503;

const TGPID_PROJECTILE_SPEED = 46;

const TGPID_PROJECITLE_GRAVITY_OVERRIDE = 1983;

const TGPID_DAMAGE_RADIUS = 6;

const TGPID_REMOTE_ACTIVATION_TIME = 7;

const TGPID_POST_LAND_DURATION = 1693;

const TGPID_PROXIMITY_DISTANCE = 8;

const TGPID_CONE_ATTACK_ANGLE = 64;

const TGPID_CONE_ATTACK_ANGLE_OFFSET = 1627;

const TGPID_EFFECTIVE_RADIUS = 343;

const TGPID_MINIMUM_RADIUS = 1048;

const TGPID_FIRE_LOCK_TIME = 437;

const TGPID_ACCURACY = 10;

const TGPID_RANGE = 5;

const TGPID_MIN_RANGE = 48;

const TGPID_WALL_JUMP_HEIGHT_INCREASE = 1966;

const TGPID_RESPAWN_TIME_REDUCTION_PERC = 1880;

const TGPID_STEALTH_SOFT_REVEAL_DISTANCE = 1881;

const TGPID_AIR_CONTROL = 1952;

const TGPID_GROUND_SPEED = 49;

const TGPID_AIR_SPEED = 70;

const TGPID_JUMP_SPEED_MODIFIER = 1782;

const TGPID_JUMP_HEIGHT_MODIFIER = 1978;

const TGPID_MOUNT_GROUND_SPEED = 1775;

const TGPID_MOUNT_TIME = 1776;

const TGPID_NO_BACKPEDAL_PENALTY = 1524;

const TGPID_KNOCKBACK = 60;

const TGPID_KNOCKUP = 1019;

const TGPID_KNOCKSTRAIGHTUP = 1435;

const TGPID_KNOCKSTRAIGHTBACK = 1761;

const TGPID_KNOCKSTRAIGHT = 2036;

const TGPID_KNOCKBACK_PLUS_GRAVITY = 1507;

const TGPID_KNOCKBACK_PLUS_GRAV_NO_CHARGE = 1961;

const TGPID_PULLIN = 1667;

const TGPID_THREAT = 420;

const TGPID_FORCE_3P_VIEW = 1654;

const TGPID_SCALE_MESH = 1810;

const TGPID_SCALE_COLLISION_HEIGHT = 1813;

const TGPID_SCALE_COLLISION_RADIUS = 1814;

const TGPID_CONFUSED = 1812;

const TGPID_POLYMORPH_CHICKEN = 1841;

const TGPID_MARK_SHOT_MARK = 1991;

const TGPID_MARK_SHOT_FIRING_AT_MARK = 1992;

const TGPID_PURSUIT_FIRING_AT_TARGET = 1999;

const TGPID_ASTRO_BUFF = 2023;

const TGPID_ENERGY_CHARGE_MULTIPLIER = 2027;

const TGPID_VISION_RANGE = 152;

const TGPID_DEVICE_MODE_BUILDUP_TIME = 2;

const TGPID_DEVICE_MODE_FIRE_TIME = 53;

const TGPID_DEVICE_MODE_COOLDOWN_TIME = 4;

const TGPID_DEVICE_MODE_TIME_TO_HOLD_BLOCK = 258;

const TGPID_DEVICE_SHOTS_PER_FIRE = 287;

const TGPID_TIME_TO_DEPLOY_SECS = 279;

const TGPID_FIRE_PRE_HIT_DELAY = 1016;

const TGPID_FIRE_POST_HIT_DELAY = 1017;

const TGPID_TUTORIAL_MAP = 368;

const TGPID_CAPTURE_TIME = 87;

const TGPID_HOLD_TIME = 88;

const TGPID_TICK_TIME = 89;

const TGPID_CAPTURE_SCORE = 97;

const TGPID_TICK_SCORE = 98;

const TGPID_STUN = 166;

const TGPID_FEAR = 1418;

const TGPID_DAZE = 1433;

const TGPID_SILENCE = 1023;

const TGPID_DISARM = 303;

const TGPID_STASIS = 1051;

const TGPID_REVEAL = 1053;

const TGPID_CRIPPLE = 1523;

const TGPID_STUNTAUNT = 1555;

const TGPID_DAMAGE_DEVICE_INTERCEPT = 1823;

const TGPID_DAMAGE_MITIGATE_INTERCEPT = 1848;

const TGPID_ON_LANDED_INTERCEPT = 1826;

const TGPID_SLOW_TO_HALT = 1558;

const TGPID_DISORIENT = 1583;

const TGPID_ENERGY_STUN = 1652;

const TGPID_STEALTH_IN_COMBAT = 1664;

const TGPID_VISIBLE_THROUGH_WALLS = 1707;

const TGPID_VISIBLE_THROUGH_WALLS_INSTIGATOR_ONLY = 1852;

const TGPID_SEE_THROUGH_WALLS = 1771;

const TGPID_VISIBLE_THROUGH_STEALTH = 1861;

const TGPID_VISIBLE_THROUGH_STEALTH_INSTIGATOR_ONLY = 1862;

const TGPID_SEE_THROUGH_STEALTH = 1863;

const TGPID_NUGGET_STEALER_FULL_HP = 1827;

const TGPID_HOVER = 1762;

const TGPID_CUSTOM_FLIGHT = 1941;

const TGPID_NO_FRICTION = 1763;

const TGPID_GRAVITY_SCALE = 1820;

const TGPID_JUMP_HANG = 1882;

const TGPID_WALL_STUN = 1764;

const TGPID_BLEEDING = 1793;

const TGPID_ON_FIRE = 1791;

const TGPID_POISONED = 1792;

const TGPID_FROZEN = 1794;

const TGPID_DECOY_AGGRO = 1944;

const TGPID_APPLY_DOTS_NOW = 1878;

const TGPID_LEAPING = 1899;

const TGPID_FALL_OUT_OF_WORLD = 1945;

const TGPID_MESMERIZE = 2019;

const TGPID_MARKED_FOR_PRESENCE = 2028;

const TGPID_PRESENCE_BUFF = 2029;

const TGPID_FLASH_BANG = 2031;

const TGPID_DISABLE_RAGDOLL = 2044;

const TGPID_REMOVE_EFFECT = 140;

const TGPID_REMOVE_ALL_DEBUFFS = 1795;

const TGPID_PERSIST_TIME = 150;

const TGPID_PERSIST_PULSE = 151;

const TGPID_CHARACTER_VISION_RANGE = 152;

const TGPID_DEVICE_EFFECTIVE_RANGE = 153;

const TGPID_MAX_DEPLOYABLES_OUT = 154;

const INDEX_DISPLAY_TARGET_MINIMAP = 0;

const INDEX_DISPLAY_TARGET_INGAME = 1;

const INDEX_DISPLAY_TARGET_BRACKET = 2;

const INDEX_DISPLAY_TARGET_DISTANCE = 3;

const INDEX_DISPLAY_TARGET_TAGGED = 4;

const INDEX_DISPLAY_SEND_AUDIO_WARNING = 5;

const INDEX_DISPLAY_TARGET_LOW_HEALTH = 6;

const INDEX_SEE_NON_MOVING_ENEMY = 0;

const INDEX_SEE_WALKING_ENEMY = 1;

const INDEX_SEE_MAKING_NOISE_ENEMY = 2;

const INDEX_SEE_FLYING_ENEMY = 3;

const INDEX_SEE_STEALTHED_ENEMY = 4;

const INDEX_SEE_DEPLOYABLES = 5;

const INDEX_SEE_BEACONS = 6;

const INDEX_SEE_BOTS_ONLY = 7;

const TGPID_PHYSICAL_IMMUNITY = 1606;

const TGPID_MAGICAL_IMMUNITY = 1607;

const TGPID_HEALTH_FLOOR = 1838;

const TGPID_BLOCK_DAMAGE_PERC = 1770;

const TGPID_FRONTAL_IMMUNITY = 1954;

const TGPID_PROTECTION_SLOW = 158;

const TGPID_PROTECTION_STUN = 163;

const TGPID_PROTECTION_KNOCKBACK = 233;

const TGPID_PROTECTION_KNOCKUP = 1837;

const TGPID_PROTECTION_FEAR = 1892;

const TGPID_PROTECTION_SILENCE = 1893;

const TGPID_PROTECTION_CC = 1591;

const TGPID_PROTECTION_ON_FIRE = 1661;

const TGPID_PROTECTION_BLEEDING = 1819;

const TGPID_PROTECTION_POISON = 1696;

const TGPID_PROTECTION_PULL = 1360;

const TGPID_PROTECTION_DOT_DURATION = 1868;

const TGPID_PROTECTION_DOT_DURATION_PERC = 1873;

const TGPID_PROTECTION_DOT_DAMAGE_PERC = 1870;

const TGPID_DEBUFF_IMMUNITY = 1796;

const TGPID_REDUCE_DEBUFF_DURATION = 1811;

const TGPID_CC_IMMUNITY = 1417;

const TGPID_CC_IMMUNITY_SUPERIOR = 1894;

const TGPID_SLOW_IMMUNITY = 1746;

const TGPID_JUMP_PENALTY_IMMUNITY = 1753;

const TGPID_TGEFFECTMODIFYEFFECT_LIFETIME = 1950;

const TGPID_TGEFFECTMODIFYEFFECT_APPVALUE = 1951;

const TGPID_TGEFFECTMODIFYEFFECT_MAXSTACK = 1989;

const TGPID_REMOVE_PROTECTION_CC = 1560;

const TGPID_HAS_HEALING_EFFECT_UI_SELF = 1959;

const TGPID_HAS_HEALING_EFFECT_UI_FRIEND = 1960;

const TGPID_MISSING_HEALTH = 211;

const TGPID_ARCING_JUMPS = 309;

const TGPID_ARC_RANGE = 1057;

const TGPID_ARC_MAX_RANGE = 1058;

const TGPID_CONTAGIOUS_RADIUS = 312;

const TGPID_PET_LIFESPAN = 354;

const TGPID_FIRE_ANGLE = 2009;

const TGPID_MAX_TARGET_COUNT = 415;

const TGPID_PROC_CHANCE_MODIFIER = 1815;

const TGPID_DOT_DURATION_PERC = 1879;

const TGPID_NEAR_DAMAGE_PERCENT = 1768;

const TGPID_FAR_DAMAGE_PERCENT = 1769;

const TGPID_AUTO_SPAWN = 170;

const TGPID_RESPAWN = 171;

const TGPID_BOT_COUNT = 172;

const TGPID_RESPAWN_DELAY = 173;

const TGPID_SPAWN_DELAY = 174;

const TGPID_TEAM_NUMBER = 175;

const TGPID_TASK_FORCE_NUMBER = 176;

const TGPID_SELECTION_METHOD = 178;

const TGPID_BOT_SELECTION_LIST = 179;

const TGPID_PLACEMENT_METHOD = 180;

const TGPID_PATROL_LOOP = 181;

const TGPID_GLOBAL_ALARM_NUMBER = 182;

const TGPID_SPAWN_LOCATION_LIST = 183;

const TGPID_PATROL_LOCATION_LIST = 184;

const TGPID_DEPLOYABLE_SELECTION_LIST = 185;

const TGPID_DESTRUCTIBLE_SELECTION_LIST = 188;

const TGPID_INSTANCE_SELECTION_LIST = 229;

const TGPID_DEVICE_SELECTION_LIST = 282;

const TGPID_NAME_SELECTION_LIST = 292;

const TGPID_BULK_SPAWN = 230;

const TGPID_LOOT_TABLE_ID = 332;

const TGPID_SPAWN_TABLE_ID = 340;

const TGPID_TIME_TO_CAPTURE = 288;

const TGPID_CAPTURE_ONLY_ONCE = 289;

const TGPID_ALLOW_AIBOT_INTERACTION = 290;

const TGPID_ALLOW_PLAYERBOT_INTERACTION = 291;

const TGPID_TIME_TO_HOLD = 294;

const TGPID_DEFENDER_RECAP_RATE = 296;

const TGPID_CAPTURE_ACCEL_RATE = 297;

const TGPID_CAPTURE_ACCEL_RATE_CAP = 298;

const TGPID_OBJECTIVE_BOT_ID = 301;

const TGPID_CAPTURE_TIME_EXTENTION = 300;

const TGPID_OVERTIME_RATE_MODIFIER = 317;

const TGPID_END_OT_ON_DEFENDER_PROGRESS = 320;

const TGPID_POINTS_PER_SECOND = 326;

const TGPID_POINTS_TO_WIN = 327;

const TGPID_OBJECTIVE_UNLOCK_DELAY = 331;

const TGPID_BLOCK_FRIENDLY_FIRE = 302;

const TGPID_TAUNT = 305;

const TGPID_BOOST_CHARGE_RATE = 337;

const TGPID_ROOT = 338;

const TGPID_CAPTURE_TIME_RESET = 358;

const TGPID_PRIORITY = 346;

const TGPID_OBJECTIVE_ID = 347;

const TGPID_MIN_AGENTS = 401;

const TGPID_POINTS = 398;

const TGPID_CREDITS = 399;

const TGPID_REWARD_XP = 400;

const TGPID_OBJECTIVE_COOLDOWN_SECONDS = 409;

const TGPID_MINIMUM_LEVEL = 410;

const TGPID_LIFT = 2030;

const TGPID_REDUCE_ACTIVE_COOLDOWN = 1554;

const TGPID_REDUCE_ACTIVE_COOLDOWN_CHILD_DEVICE = 1840;

const TGPID_REDUCE_ACTIVE_COOLDOWN_CHILD_ITEMS = 1942;

const TGPID_AMMO_COUNT = 424;

const TGPID_AMMO_CLIP_PRE_RELOAD_TIME = 435;

const TGPID_AMMO_CLIP_POST_RELOAD_TIME = 425;

const TGPID_AMMO_CLIP_SIZE = 426;

const TGPID_AMMO_REPLENISH = 427;

const TGPID_AMMO_COST_PER_SHOT = 1853;

const TGPID_AMMO_REGEN_PER_SEC = 1854;

const TGPID_DROGOZ_ENERGY = 1886;

const TGPID_DROGOZ_ENERGY_MAX = 1887;

const TGPID_ORACLE_ORB_STACK = 1993;

const TGPID_HEALTH = 51;

const TGPID_HEALTH_MAX = 304;

const TGPID_HEALTH_MAX_PERCENT = 1620;

const TGPID_HP5 = 1011;

const TGPID_HP5_PERCENT = 1565;

const TGPID_HP5_PERCENT_OF_MAX_HEALTH = 1772;

const TGPID_MANA_MAX = 1001;

const TGPID_MANA = 1002;

const TGPID_MP5 = 1003;

const TGPID_ENERGY = 1004;

const TGPID_ENERGY_MAX = 1005;

const TGPID_EP5 = 1006;

const TGPID_SHIELD = 1598;

const TGPID_SHIELD_MAX = 1599;

const TGPID_SHIELD_MAX_INSTIGATOR_SCALE = 1612;

const TGPID_POWER_PHYSICAL_BOT = 1082;

const TGPID_POWER_PHYSICAL_ITEM = 1007;

const TGPID_POWER_PHYSICAL_PERC = 1047;

const TGPID_POWER_MAGICAL_BOT = 1083;

const TGPID_POWER_MAGICAL_ITEM = 1008;

const TGPID_POWER_MAGICAL_PERC = 1046;

const TGPID_POWER_UTILITY_BOT = 1484;

const TGPID_POWER_UTILITY_ITEM = 1485;

const TGPID_LIFESTEAL = 1010;

const TGPID_LIFESTEAL_INSTIGATOR_ONLY = 1898;

const TGPID_LIFESTEAL_VENGEANCE_TARGET = 2006;

const TGPID_HEALTH_COST = 1578;

const TGPID_MANA_COST = 1012;

const TGPID_ENERGY_COST = 1013;

const TGPID_MINIMAP_LOS_IGNORED = 1032;

const TGPID_MINIMAP_DETECTOR = 1033;

const TGPID_HEALTH_PERCENT = 1044;

const TGPID_MANA_PERCENT = 1045;

const TGPID_SHIELD_PERCENT = 1988;

const TGPID_CUSTOM_VALUE_1 = 1049;

const TGPID_CUSTOM_VALUE_2 = 1050;

const TGPID_CUSTOM_VALUE_3 = 1594;

const TGPID_CUSTOM_VALUE_4 = 1595;

const TGPID_CUSTOM_VALUE_5 = 1596;

const TGPID_FIRE_HOLD_TIME = 1757;

const TGPID_FIRE_HOLD_RATE = 1963;

const TGPID_FIRE_HOLD_ACCURACY_PERC_LOW = 1758;

const TGPID_FIRE_HOLD_DAMAGE_PERC_LOW = 1759;

const TGPID_SLOW_DIMINISHING = 1231;

const TGPID_SLOW_CAP_PERC = 1948;

const TGPID_MARKED = 1839;

const TGPID_MARKED_INHAND = 1970;

const TGPID_HEALING_TAKEN_PERC = 1056;

const TGPID_HEALING_TAKEN_OTHERS_PERC = 1947;

const TGPID_DAMAGE_TAKEN_PERC = 316;

const TGPID_DAMAGE_TAKEN_PERC_INHAND = 1665;

const TGPID_DAMAGE_TAKEN_PERC_AOE = 1765;

const TGPID_DAMAGE_TAKEN_PERC_DIRECT = 1949;

const TGPID_DAMAGE_TAKEN_PERC_PHYS = 1630;

const TGPID_DAMAGE_CAP_PERC_MAX_HP = 1857;

const TGPID_DAMAGE_CAP_PERC_CUR_HP = 1858;

const TGPID_DAMAGE_REDUCTION_FLAT = 1874;

const TGPID_DAMAGE_REDUCTION_PERC = 1990;

const TGPID_DAMAGE_REDUCTION_PERC_INHAND = 1997;

const TGPID_DAMAGE_REDUCTION_PERC_AOE = 1996;

const TGPID_DAMAGE_REDUCTION_PERC_DIRECT = 1995;

const TGPID_DAMAGE_REDUCTION_PERC_PHYS = 1994;

const TGPID_DAMAGE_REDUCTION_PERC_MAG = 1998;

const TGPID_DAMAGE_AMP_PERC = 2000;

const TGPID_DAMAGE_AMP_PERC_INHAND = 2005;

const TGPID_DAMAGE_AMP_PERC_AOE = 2002;

const TGPID_DAMAGE_AMP_PERC_DIRECT = 2001;

const TGPID_DAMAGE_AMP_PERC_PHYS = 2003;

const TGPID_DAMAGE_AMP_PERC_MAG = 2004;

const TGPID_DAMAGE_AMP_FAIRY = 2007;

const TGPID_DAMAGE_DEALT_PERC = 65;

const TGPID_DAMAGE_DEALT_PERC_BASIC = 1605;

const TGPID_DAMAGE_DEALT_PERC_PHYSICAL = 1864;

const TGPID_DAMAGE_DEALT_PERC_MAGICAL = 1865;

const TGPID_DAMAGE_DEALT_PERC_DEPLOYABLES = 1859;

const TGPID_DAMAGE_DEALT_PERC_SHIELDS = 1860;

const TGPID_DAMAGE_DEALT_FLAT = 1875;

const TGPID_HEAL_BLOCK = 1877;

const TGPID_STEALTH = 1416;

const TGPID_STEALTH_GUARD = 1832;

const TGPID_STEALTH_WITHFADING = 1597;

const TGPID_STEALTH_DISABLED = 141;

const TGPID_STEALTH_NO_REVEAL = 1660;

const TGPID_BREAK_GRAB = 1556;

const TGPID_GP_SURRENDER_TIME = 1386;

const TGPID_GP_STARTING_GOLD = 1426;

const TGPID_GP_STARTING_LEVEL = 1427;

const TGPID_GP_GOLD_SPOOL = 1500;

const TGPID_GP_XP_SPOOL = 1501;

const TGPID_GP_ENABLE_NEW_FOW = 1568;

const TGPID_GP_MAX_RESPAWN_TIME = 1569;

const TGPID_GP_GOD_XP_COEFFICIENT = 1581;

const TGPID_INHAND_EFFECTIVE_RANGE = 1684;

const TGPID_INHAND_ABSOLUTE_RANGE = 1685;

const TGPID_INHAND_AMMO_CAPACITY = 1687;

const TGPID_INHAND_RELOAD_SPEED = 1688;

const TGPID_INHAND_REFIRE_SPEED = 1699;

const TGPID_INHAND_EFFECTIVE_AOE = 1689;

const TGPID_INHAND_ABSOLUTE_AOE = 1690;

const TGPID_INHAND_RESTORE_AMMO = 1855;

const TGPID_OUT_OF_COMBAT = 1694;

const TGPID_ENTER_COMBAT = 1700;

const TGPID_COMBAT_DURATION_REDUCTION_PERC = 1703;

const TGPID_IGNORE_ACTOR_BLOCKING = 1745;

const TGPID_ETHEREAL = 1821;

const TGPID_INHAND_FIRE_OVERRIDE = 1822;

const TGPID_AI_DEVICE_RANGE = 1486;

const TGPID_AI_DEVICE_RADIUS = 1487;

const TGPID_HEAD_SHOT_DAMAGE = 1905;

const TGPID_AI_ACCURACY_PERC = 1888;

const TGPID_AI_ACCURACY_DEG_MISSED = 1889;

const TGPID_CONFIG_SETTING_GAMEPAD_X_SENSITIVITY = 1971;

const TGPID_CONFIG_SETTING_GAMEPAD_Y_SENSITIVITY = 1972;

const TGPID_CONFIG_SETTING_GAMEPAD_AIM_ACCEL_MODE = 1973;

const TGPID_CONFIG_SETTING_GAMEPAD_AIM_ACCEL_BOOST = 1974;

const TGPID_CONFIG_SETTING_GAMEPAD_AIM_ASSIST_MAGNET = 1975;

const TGPID_CONFIG_SETTING_GAMEPAD_AIM_ASSIST_TRACKING = 1976;

const TGPID_CONFIG_SETTING_GAMEPAD_DEAD_ZONE_INNER = 1984;

const TGPID_CONFIG_SETTING_GAMEPAD_DEAD_ZONE_OUTER = 1985;

const TGPID_CONFIG_SETTING_SCOPE_SENSITIVITY = 2042;

const PROTECTION_IMMUNITY_VALUE = 100;

const PROTECTION_DAMAGE_IMMUNITY_VALUE = 10000;

enum TG_PAWN_PROPERTIES {
    TGPIDX_CHARACTER_VISION_RANGE,  // 0
    TGPIDX_ENERGY_MAX,  // 1
    TGPIDX_ENERGY,  // 2
    TGPIDX_EP5,  // 3
    TGPIDX_WALL_JUMP_HEIGHT_INCREASE,  // 4
    TGPIDX_RESPAWN_TIME_REDUCTION_PERC,  // 5
    TGPIDX_STEALTH_SOFT_REVEAL_DISTANCE,  // 6
    TGPIDX_AIR_CONTROL,  // 7
    TGPIDX_GROUND_SPEED,  // 8
    TGPIDX_AIR_SPEED,  // 9
    TGPIDX_JUMP_SPEED_MODIFIER,  // 10
    TGPIDX_JUMP_HEIGHT_MODIFIER,  // 11
    TGPIDX_MOUNT_GROUND_SPEED,  // 12
    TGPIDX_MOUNT_TIME,  // 13
    TGPIDX_DROGOZ_ENERGY,  // 14
    TGPIDX_DROGOZ_ENERGY_MAX,  // 15
    TGPIDX_ORACLE_ORB_STACK,  // 16
    TGPIDX_HEALTH_MAX,  // 17
    TGPIDX_HEALTH_MAX_PERCENT,  // 18
    TGPIDX_HEALTH,  // 19
    TGPIDX_HP5,  // 20
    TGPIDX_MANA_MAX,  // 21
    TGPIDX_MANA,  // 22
    TGPIDX_MP5,  // 23
    TGPIDX_STEALTH_GUARD,  // 24
    TGPIDX_VISIBLE_THROUGH_WALLS,  // 25
    TGPIDX_VISIBLE_THROUGH_WALLS_INSTIGATOR_ONLY,  // 26
    TGPIDX_SEE_THROUGH_WALLS,  // 27
    TGPIDX_VISIBLE_THROUGH_STEALTH,  // 28
    TGPIDX_VISIBLE_THROUGH_STEALTH_INSTIGATOR_ONLY,  // 29
    TGPIDX_SEE_THROUGH_STEALTH,  // 30
    TGPIDX_NUGGET_STEALER_FULL_HP,  // 31
    TGPIDX_HOVER,  // 32
    TGPIDX_CUSTOM_FLIGHT,  // 33
    TGPIDX_NO_FRICTION,  // 34
    TGPIDX_GRAVITY_SCALE,  // 35
    TGPIDX_JUMP_HANG,  // 36
    TGPIDX_SHIELD,  // 37
    TGPIDX_SHIELD_MAX,  // 38
    TGPIDX_LIFESTEAL,  // 39
    TGPIDX_LIFESTEAL_INSTIGATOR_ONLY,  // 40
    TGPIDX_LIFESTEAL_VENGEANCE_TARGET,  // 41
    TGPIDX_POWER_MAGICAL_BOT,  // 42
    TGPIDX_POWER_PHYSICAL_BOT,  // 43
    TGPIDX_PROTECTION_FEAR,  // 44
    TGPIDX_PROTECTION_KNOCKBACK,  // 45
    TGPIDX_PROTECTION_KNOCKUP,  // 46
    TGPIDX_PROTECTION_SILENCE,  // 47
    TGPIDX_PROTECTION_SLOW,  // 48
    TGPIDX_PROTECTION_STUN,  // 49
    TGPIDX_PROTECTION_PULL,  // 50
    TGPIDX_PROTECTION_CC,  // 51
    TGPIDX_PROTECTION_ON_FIRE,  // 52
    TGPIDX_PROTECTION_BLEEDING,  // 53
    TGPIDX_PROTECTION_POISON,  // 54
    TGPIDX_PROTECTION_DOT_DURATION,  // 55
    TGPIDX_PROTECTION_DOT_DURATION_PERC,  // 56
    TGPIDX_PROTECTION_DOT_DAMAGE_PERC,  // 57
    TGPIDX_DEBUFF_IMMUNITY,  // 58
    TGPIDX_REDUCE_DEBUFF_DURATION,  // 59
    TGPIDX_CC_IMMUNITY,  // 60
    TGPIDX_CC_IMMUNITY_SUPERIOR,  // 61
    TGPIDX_SLOW_IMMUNITY,  // 62
    TGPIDX_JUMP_PENALTY_IMMUNITY,  // 63
    TGPIDX_TAUNT,  // 64
    TGPIDX_POWER_PHYSICAL_PERC,  // 65
    TGPIDX_POWER_MAGICAL_PERC,  // 66
    TGPIDX_HEALING_TAKEN_PERC,  // 67
    TGPIDX_HEALING_TAKEN_OTHERS_PERC,  // 68
    TGPIDX_DAMAGE_TAKEN_PERC,  // 69
    TGPIDX_DAMAGE_DEALT_PERC,  // 70
    TGPIDX_DAMAGE_DEALT_PERC_BASIC,  // 71
    TGPIDX_DAMAGE_DEALT_PERC_PHYSICAL,  // 72
    TGPIDX_DAMAGE_DEALT_PERC_MAGICAL,  // 73
    TGPIDX_DAMAGE_DEALT_PERC_DEPLOYABLES,  // 74
    TGPIDX_DAMAGE_DEALT_PERC_SHIELDS,  // 75
    TGPIDX_DAMAGE_DEALT_FLAT,  // 76
    TGPIDX_POWER_PHYSICAL_ITEM,  // 77
    TGPIDX_POWER_MAGICAL_ITEM,  // 78
    TGPIDX_POWER_UTILITY_BOT,  // 79
    TGPIDX_POWER_UTILITY_ITEM,  // 80
    TGPIDX_SLOW_DIMINISHING,  // 81
    TGPIDX_MARKED,  // 82
    TGPIDX_MARKED_INHAND,  // 83
    TGPIDX_MINIMAP_LOS_IGNORED,  // 84
    TGPIDX_MINIMAP_DETECTOR,  // 85
    TGPIDX_BLOCK_DAMAGE_PERC,  // 86
    TGPIDX_FRONTAL_IMMUNITY,  // 87
    TGPIDX_NO_BACKPEDAL_PENALTY,  // 88
    TGPIDX_HP5_PERC,  // 89
    TGPIDX_HP5_PERC_OF_MAX_HEALTH,  // 90
    TGPIDX_PHYSICAL_IMMUNITY,  // 91
    TGPIDX_MAGICAL_IMMUNITY,  // 92
    TGPIDX_DAMAGE_TAKEN_PERC_PHYS,  // 93
    TGPIDX_DAMAGE_TAKEN_PERC_INHAND,  // 94
    TGPIDX_DAMAGE_TAKEN_PERC_AOE,  // 95
    TGPIDX_DAMAGE_TAKEN_PERC_DIRECT,  // 96
    TGPIDX_DAMAGE_REDUCTION_FLAT,  // 97
    TGPIDX_DAMAGE_REDUCTION_PERC,  // 98
    TGPIDX_DAMAGE_REDUCTION_PERC_INHAND,  // 99
    TGPIDX_DAMAGE_REDUCTION_PERC_AOE,  // 100
    TGPIDX_DAMAGE_REDUCTION_PERC_DIRECT,  // 101
    TGPIDX_DAMAGE_REDUCTION_PERC_PHYS,  // 102
    TGPIDX_DAMAGE_REDUCTION_PERC_MAG,  // 103
    TGPIDX_DAMAGE_AMP_PERC,  // 104
    TGPIDX_DAMAGE_AMP_PERC_INHAND,  // 105
    TGPIDX_DAMAGE_AMP_PERC_AOE,  // 106
    TGPIDX_DAMAGE_AMP_PERC_DIRECT,  // 107
    TGPIDX_DAMAGE_AMP_PERC_PHYS,  // 108
    TGPIDX_DAMAGE_AMP_PERC_MAG,  // 109
    TGPIDX_DAMAGE_AMP_FAIRY,  // 110
    TGPIDX_HEAL_BLOCK,  // 111
    TGPIDX_INHAND_RELOAD_SPEED,  // 112
    TGPIDX_INHAND_AMMO_CAPACITY,  // 113
    TGPIDX_INHAND_REFIRE_SPEED,  // 114
    TGPIDX_COMBAT_DURATION_REDUCTION_PERC,  // 115
    TGPIDX_IGNORE_ACTOR_BLOCKING,  // 116
    TGPIDX_FORCE_3P_VIEW,  // 117
    TGPIDX_SCALE_MESH,  // 118
    TGPIDX_SCALE_COLLISION_HEIGHT,  // 119
    TGPIDX_SCALE_COLLISION_RADIUS,  // 120
    TGPIDX_CONFUSED,  // 121
    TGPIDX_NEAR_DAMAGE_PERCENT,  // 122
    TGPIDX_FAR_DAMAGE_PERCENT,  // 123
    TGPIDX_BLEEDING,  // 124
    TGPIDX_ON_FIRE,  // 125
    TGPIDX_POISONED,  // 126
    TGPIDX_FROZEN,  // 127
    TGPIDX_INHAND_EFFECTIVE_AOE,  // 128
    TGPIDX_INHAND_ABSOLUTE_AOE,  // 129
    TGPIDX_PROC_CHANCE_MODIFIER,  // 130
    TGPIDX_DOT_DURATION_PERC,  // 131
    TGPIDX_ETHEREAL,  // 132
    TGPIDX_INHAND_FIRE_OVERRIDE,  // 133
    TGPIDX_HEALTH_FLOOR,  // 134
    TGPIDX_LEAPING,  // 135
    TGPIDX_DECOY_AGGRO,  // 136
    TGPIDX_HAS_HEALING_EFFECT_UI_SELF,  // 137
    TGPIDX_HAS_HEALING_EFFECT_UI_FRIEND,  // 138
    TGPIDX_MARK_SHOT_MARK,  // 139
    TGPIDX_MARK_SHOT_FIRING_AT_MARK,  // 140
    TGPIDX_PURSUIT_FIRING_AT_TARGET,  // 141
    TGPIDX_MESMERIZE,  // 142
    TGPIDX_MARKED_FOR_PRESENCE,  // 143
    TGPIDX_PRESENCE_BUFF,  // 144
    TGPIDX_DISABLE_RAGDOLL,  // 145
};

var int m_nPropIndex;
var int m_nPropertyId;
var float m_fBase;
var float m_fRaw;
var float m_fMinimum;
var float m_fMaximum;
var float m_fScalingFactor;

native function float GetCurrentValue();  // Export UTgProperty::execGetCurrentValue(FFrame&, void* const)

simulated event Copy(TgProperty pProperty) { }

native function int GetPropIndex(int propId);  // Export UTgProperty::execGetPropIndex(FFrame&, void* const)

native function int GetPropIndexByName(string propName);  // Export UTgProperty::execGetPropIndexByName(FFrame&, void* const)
