#!/usr/bin/env bash
#
# dump_roster.sh — extract the full champion roster + all cards/talents from a
# Paladins Assembly database and emit ready-to-paste UnrealScript for TmCore.
#
# Emits:
#   1. AddChampion(...)  lines for every real champion (body skin + head skin
#      + a "Default <X> WEP" weapon) in GetAllChampions().
#   2. AddLoadout(...)   lines for every champion with a default loadout
#      (first non-deprecated talent + the 5 "core" card groups at their max
#      rank) in GetAllLoadouts().
#   3. With --cards: a commented dump of EVERY card (grouped I/II/III/IV) and
#      every talent per champion, so you can hand-pick different defaults.
#
# Usage:
#   tool/dump_roster.sh <assembly.db> <LANG.db> [--cards] [--only Name,...]
#
# Example:
#   tool/dump_roster.sh \
#     "$HOME/Library/Application Support/tempest-launcher-electron/instances/03d1c0b7-31ea-4edc-9e0d-d4fc9037b55e/assembly.db" \
#     "$HOME/Library/Application Support/tempest-launcher-electron/instances/03d1c0b7-31ea-4edc-9e0d-d4fc9037b55e/LANG.db"
#
# Depends only on python3 (stdlib sqlite3).

set -euo pipefail

ASM="${1:-}"
LANG="${2:-}"
shift 2 2>/dev/null || true

CARDS=0
ONLY=""

for arg in "$@"; do
    case "$arg" in
        --cards) CARDS=1 ;;
        --only)  ONLY="${2:-}"; shift ;;
        --only=*) ONLY="${arg#*=}" ;;
    esac
done

if [[ -z "$ASM" || -z "$LANG" ]]; then
    echo "Usage: $0 <assembly.db> <LANG.db> [--cards] [--only Name,...]" >&2
    exit 1
fi
if [[ ! -f "$ASM" ]]; then echo "assembly.db not found: $ASM" >&2; exit 1; fi
if [[ ! -f "$LANG" ]]; then echo "LANG.db not found: $LANG" >&2; exit 1; fi

ASM="$ASM" LANG="$LANG" CARDS="$CARDS" ONLY="$ONLY" python3 << 'PYEOF'
import os, re, sqlite3, sys

asm_path = os.environ["ASM"]
lang_path = os.environ["LANG"]
show_cards = os.environ.get("CARDS") == "1"
only_raw = os.environ.get("ONLY", "").strip()
only = {re.sub(r"\s+", "", n).lower() for n in only_raw.split(",")} if only_raw else None

asm = sqlite3.connect(asm_path)
lang = sqlite3.connect(lang_path)

def lname(msg_id):
    if msg_id is None:
        return None
    row = lang.execute("SELECT MESSAGE FROM DATA_SET WHERE MSG_ID=?", (msg_id,)).fetchone()
    return row[0] if row else None

def esc(s):
    # UnrealScript double-quoted string: escape backslash + double quote.
    return s.replace("\\", "\\\\").replace('"', '\\"')

# ---- Champion identity -------------------------------------------------
bots = asm.execute("""
    SELECT BOT_ID, REFERENCE_NAME, PAWN_CLASS_RES_ID,
           DEFAULT_SKIN_ITEM_ID, DEFAULT_HEAD_SKIN_ITEM_ID
    FROM DATA_SET_BOTS ORDER BY BOT_ID
""").fetchall()

RANK = {"i": 1, "ii": 2, "iii": 3, "iv": 4}
RANK_NAME = {1: "I", 2: "II", 3: "III", 4: "IV"}
RANK_RE = re.compile(r"^(.*?)\s*(IV|III|II|I)$", re.I)

def get_weapon(bot):
    rows = asm.execute(
        "SELECT ITEM_ID, NAME_MSG_ID FROM DATA_SET_ITEMS WHERE REF_BOT_ID=? AND ITEM_TYPE_VALUE_ID=15041",
        (bot,)).fetchall()
    for iid, mid in rows:
        nm = lname(mid)
        if nm and "default" in nm.lower():
            return iid
    # Fallback: lowest item id.
    return min((r[0] for r in rows), default=None) if rows else None

def get_voice(bot):
    # Voice packs appear as item type 10637 (and 15170 in newer schemas).
    for itype in (10637, 15170):
        row = asm.execute(
            "SELECT MIN(ITEM_ID) FROM DATA_SET_ITEMS WHERE REF_BOT_ID=? AND ITEM_TYPE_VALUE_ID=?",
            (bot, itype)).fetchone()
        if row and row[0]:
            return row[0]
    return 0

def get_cards_talents(bot):
    """Returns (groups, talents). groups: base_name -> {rank: item_id}.
    talents: list of (item_id, name). Skips zDeprecated/zOld."""
    rows = asm.execute(
        "SELECT ITEM_ID, NAME_MSG_ID FROM DATA_SET_ITEMS WHERE REF_BOT_ID=? AND ITEM_TYPE_VALUE_ID=217",
        (bot,)).fetchall()
    groups = {}
    talents = []
    for iid, mid in rows:
        nm = lname(mid)
        if not nm or nm.lower().startswith("z"):
            continue
        m = RANK_RE.match(nm)
        if m:
            base = m.group(1).strip()
            rank = RANK[m.group(2).lower()]
            groups.setdefault(base, {})[rank] = iid
        else:
            talents.append((iid, nm))
    return groups, talents

champions = []
for bot, ref, pawn, skin, head in bots:
    if not skin or not head or skin <= 0 or head <= 0:
        continue
    wep = get_weapon(bot)
    if wep is None:
        continue
    groups, talents = get_cards_talents(bot)
    if not groups and not talents:
        continue
    if only is not None and re.sub(r"\s+", "", ref.lower()) not in only:
        continue
    champions.append((bot, ref, pawn, skin, head, wep, groups, talents))

# ---- Emission ----------------------------------------------------------
print("// Auto-generated by tool/dump_roster.sh")
print(f"// assembly.db = {asm_path}")
print(f"// LANG.db     = {lang_path}")
print()

# 1. Champions
print("// ==== GetAllChampions(): AddChampion lines ====")
print("// Add aliases as the trailing optional args if you want them.")
for bot, ref, pawn, skin, head, wep, groups, talents in champions:
    voice = get_voice(bot)
    print(f'AddChampion(List, "{esc(ref)}", {bot}, {pawn}, {skin}, {head}, {wep}, {voice});')
print()

# 2. Default loadouts
print("// ==== GetAllLoadouts(): AddLoadout lines (default = first talent + 5 core cards @ max rank) ====")
print("// Edit the card/talent names to taste — see the --cards dump below.")
for bot, ref, pawn, skin, head, wep, groups, talents in champions:
    if not talents:
        print(f'// {esc(ref)} ({bot}): no talent found — add AddLoadout manually')
        continue
    # Default talent: first non-deprecated by item id.
    talent = sorted(talents)[0][1]
    # Default cards: the 5 base-groups with the lowest min-rank item id, at max rank.
    chosen = sorted(groups.keys(), key=lambda b: min(groups[b].values()))[:5]
    if not chosen:
        print(f'// {esc(ref)} ({bot}): no cards found')
        continue
    picks = []
    for base in chosen:
        rk = max(groups[base].keys())
        picks.append(f"{base} {RANK_NAME[rk]}")
    args = ", ".join(f'"{esc(x)}"' for x in [talent] + picks)
    print(f"AddLoadout(List, {bot}, {args});")
print()

# 3. Full card / talent reference (optional)
if show_cards:
    print("// ==== ALL cards & talents per champion (reference) ====")
    for bot, ref, pawn, skin, head, wep, groups, talents in champions:
        print(f"// --- {ref} (bot {bot}) ---")
        for iid, nm in sorted(talents):
            print(f'//   TALENT {iid}: "{esc(nm)}"')
        for base in sorted(groups, key=lambda b: min(groups[b].values())):
            g = groups[base]
            items = ", ".join(
                f'{RANK_NAME[rk]}={g[rk]}' for rk in sorted(g.keys()))
            print(f'//   CARD   "{esc(base)}": {items}')
        print()
PYEOF
